version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: axora_container_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  container_microservice:
    build: .
    container_name: container_microservice
    depends_on:
      - postgres
    environment:
      POSTGRES_CONNECTION_STRING: Host=postgres;Port=5433;Database=axora_container_db;Username=postgres;Password=12345678
      RESET_DATABASE: "true"
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data:
